export const responseDb = {
    "page": 1,
    "results": [{
        "adult": false,
        "backdrop_path": "/p1F51Lvj3sMopG948F5HsBbl43C.jpg",
        "genre_ids": [28, 12, 14],
        "id": 616037,
        "original_language": "en",
        "original_title": "Thor: Love and Thunder",
        "overview": "Тор  отправляется в путешествие, не похожее ни на что из того, с чем он когда-либо сталкивался, — в поисках внутреннего спокойствия. Но его выход на пенсию прерывается Горром Убийцей богов, который стремится уничтожить богов. Чтобы справиться с угрозой, Тор обращается за помощью к Валькирии, Коргу и бывшей подруге Джейн Фостер, которая, к удивлению Тора, необъяснимым образом владеет своим волшебным молотом Мьёльниром. Вместе они отправляются в душераздирающее космическое приключение, чтобы раскрыть тайну Горра и остановить его, пока не стало слишком поздно.",
        "popularity": 8634.911,
        "poster_path": "/80ekusNlTdZO5hb9fKsFSCA7k4X.jpg",
        "release_date": "2022-07-08",
        "title": "Тор: Любовь и гром",
        "video": false,
        "vote_average": 6.8,
        "vote_count": 1862
    }, {
        "adult": false,
        "backdrop_path": "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
        "genre_ids": [10751, 16, 12, 35, 14],
        "id": 438148,
        "original_language": "en",
        "original_title": "Minions: The Rise of Gru",
        "overview": "Миллион лет миньоны искали самого великого и ужасного предводителя, пока не встретили ЕГО. Знакомьтесь - Грю. Пусть он еще очень молод, но у него в планах по-настоящему гадкие дела, которые заставят планету содрогнуться.",
        "popularity": 7863.696,
        "poster_path": "/19GXuePqcZSPD5JgT9MeVdeu9Tc.jpg",
        "release_date": "2022-06-30",
        "title": "Миньоны: Грювитация",
        "video": false,
        "vote_average": 7.8,
        "vote_count": 1359
    }, {
        "adult": false,
        "backdrop_path": "/9eAn20y26wtB3aet7w9lHjuSgZ3.jpg",
        "genre_ids": [12, 28, 878],
        "id": 507086,
        "original_language": "en",
        "original_title": "Jurassic World Dominion",
        "overview": "После уничтожения острова Нублар динозавры вырвались на свободу и стали полноправными обитателями планеты. Людям удается поддерживать хрупкое равновесие, определяющее мирное сосуществование на Земле. Но как долго человек сможет сохранять свое господство, живя по соседству с самыми устрашающими существами в истории?",
        "popularity": 5736.316,
        "poster_path": "/6BLMT9T4wRu5QlnqVeQUU5WApLj.jpg",
        "release_date": "2022-06-09",
        "title": "Мир Юрского периода: Господство",
        "video": false,
        "vote_average": 7.1,
        "vote_count": 2782
    }, {
        "adult": false,
        "backdrop_path": "/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
        "genre_ids": [27, 53],
        "id": 756999,
        "original_language": "en",
        "original_title": "The Black Phone",
        "overview": "Детоубийца похищает 13-летнего подростка и запирает его в звуконепроницаемом подвале. Вскоре парню начинает звонить по отключенному телефону предыдущая жертва убийцы.",
        "popularity": 3359.348,
        "poster_path": "/fWGd2NCgrwsammIxBJ2AhoffVkS.jpg",
        "release_date": "2022-06-24",
        "title": "Чёрный телефон",
        "video": false,
        "vote_average": 8,
        "vote_count": 1843
    }, {
        "adult": false,
        "backdrop_path": "/l99dylTOAMkwKSr54X5ytiEtnLA.jpg",
        "genre_ids": [14, 12, 28],
        "id": 919355,
        "original_language": "en",
        "original_title": "Dragon Knight",
        "overview": "Когда злобная сила овладевает королевствами Агоноса, одинокий рыцарь должен отправиться в опасное путешествие, чтобы найти последнего дракона и спасти мир от этого великого и возрастающего зла.",
        "popularity": 1913.939,
        "poster_path": "/zzwbRDElG1BmQ0WpSBl5cfrPpO4.jpg",
        "release_date": "2022-06-25",
        "title": "Повелитель Дракона",
        "video": false,
        "vote_average": 7.1,
        "vote_count": 22
    }, {
        "adult": false,
        "backdrop_path": "/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg",
        "genre_ids": [28, 12, 878],
        "id": 634649,
        "original_language": "en",
        "original_title": "Spider-Man: No Way Home",
        "overview": "Жизнь и репутация Питера Паркера оказываются под угрозой, поскольку Мистерио раскрыл всему миру тайну личности Человека-паука. Пытаясь исправить ситуацию, Питер обращается за помощью к Стивену Стрэнджу, но вскоре всё становится намного опаснее.",
        "popularity": 1826.631,
        "poster_path": "/3hLU5V1XDF0oHT9YUHvYC4j0Ix5.jpg",
        "release_date": "2021-12-15",
        "title": "Человек-паук: Нет пути домой",
        "video": false,
        "vote_average": 8,
        "vote_count": 14660
    }, {
        "adult": false,
        "backdrop_path": "/ftGzl2GCyko61Qp161bQElN2Uzd.jpg",
        "genre_ids": [28, 53],
        "id": 961484,
        "original_language": "en",
        "original_title": "Last Seen Alive",
        "overview": "Уилл и Лиза, супруги на грани развода, едут к ее родителям, но во время остановки на заправке девушка бесследно исчезает. Не выдержала напряжения и сбежала? Была похищена? Или у Уилла сдали нервы?.. Ни полиция, ни родители Лизы не в курсе ее местонахождения, и все серьезнее подозревают Уилла. Тому приходится взять дело в свои руки и исследовать криминальную изнанку города, чтобы найти Лизу...",
        "popularity": 1783.891,
        "poster_path": "/63UcA8xZ92d1IZbAgKMhJQREA2F.jpg",
        "release_date": "2022-06-09",
        "title": "Пропавшая",
        "video": false,
        "vote_average": 6.6,
        "vote_count": 229
    }, {
        "adult": false,
        "backdrop_path": "/rLo9T9jEg67UZPq3midjLnTUYYi.jpg",
        "genre_ids": [10402, 18, 36],
        "id": 614934,
        "original_language": "en",
        "original_title": "Elvis",
        "overview": "История жизни и музыки Элвиса Пресли через призму сложных взаимоотношений с его менеджером, полковником Томом Паркером. Они работали вместе более 20 лет: от начала карьеры Элвиса до его небывалой славы.",
        "popularity": 1587.217,
        "poster_path": "/2XivHQRESfGDacin0bzlkAVNggV.jpg",
        "release_date": "2022-07-14",
        "title": "Элвис",
        "video": false,
        "vote_average": 7.9,
        "vote_count": 994
    }, {
        "adult": false,
        "backdrop_path": "/1Ds7xy7ILo8u2WWxdnkJth1jQVT.jpg",
        "genre_ids": [28, 12, 35],
        "id": 752623,
        "original_language": "en",
        "original_title": "The Lost City",
        "overview": "Блистательная затворница Лоретта Сейдж пишет популярные любовно-приключенческие романы. События в них непременно разворачиваются в экзотических местах, а главный герой — красавчик и мечта героинь Дэш, которого в жизни воплощает модель с обложки Алан. Во время турне-презентации нового бестселлера Лоретту похищает эксцентричный миллиардер, уверенный, что она сможет привести его к сокровищам древнего затерянного города из ее последней книги. Алан решает доказать, что может быть героем в реальной жизни, а не только на страницах книг, и отправляется Лоретте на выручку. Так странная парочка ввязывается в эпичное приключение в самом сердце джунглей и должна действовать сообща, если хочет пережить дикие испытания и найти сокровище, пока оно не затерялось навсегда.",
        "popularity": 1357.772,
        "poster_path": "/dclMTtcF8PgZA59LTIQrMRFuHai.jpg",
        "release_date": "2022-04-07",
        "title": "Затерянный город",
        "video": false,
        "vote_average": 6.8,
        "vote_count": 1753
    }, {
        "adult": false,
        "backdrop_path": "/b1L7qevxiVpkVFq4dmdQPGFPWH0.jpg",
        "genre_ids": [27],
        "id": 836225,
        "original_language": "en",
        "original_title": "The Exorcism of God",
        "overview": "Американский священник Питер Уильямс, работающий в Мексике, среди многих местных прихожан считается святым. Однако после давнего случая экзорцизма он хранит страшную тайну, которая подтачивает его изнутри. И вот спустя 18 лет ему придётся снова встретиться с тем демоном.",
        "popularity": 1348.451,
        "poster_path": "/o9c6SrQTqGnlONZmRY7qmjAYxwj.jpg",
        "release_date": "2022-03-31",
        "title": "Последнее пришествие дьявола",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 523
    }, {
        "adult": false,
        "backdrop_path": "/2oXQpm0wfOkIL0jBJABbL5AfMs6.jpg",
        "genre_ids": [27, 9648, 53],
        "id": 760104,
        "original_language": "en",
        "original_title": "X",
        "overview": "1979 год. Группа людей приезжает на ферму в Техасе, чтобы снимать фильм для взрослых. Хозяева дома, пожилая пара, вскоре начинают охоту за приехавшими.",
        "popularity": 1332.429,
        "poster_path": "/woTQx9Q4b8aO13jR9dsj8C9JESy.jpg",
        "release_date": "2022-03-17",
        "title": "Икс (X)",
        "video": false,
        "vote_average": 6.7,
        "vote_count": 733
    }, {
        "adult": false,
        "backdrop_path": "/C8FpZfTPEZDjngPlatiFsaDB4A.jpg",
        "genre_ids": [28, 35, 80],
        "id": 718930,
        "original_language": "en",
        "original_title": "Bullet Train",
        "overview": "Сюжет фильма разворачивается вокруг группы наёмников и киллеров, оказавшихся на высокоскоростном поезде из Токио в Мариоку. Когда те обнаруживают, что все их задания связаны с одним и тем же загадочным чемоданом, между ними завязывается масштабный конфликт.",
        "popularity": 1205.877,
        "poster_path": "/jMopD87ALAbEjhYznqTL5QBJu5T.jpg",
        "release_date": "2022-08-04",
        "title": "Быстрее пули",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 305
    }, {
        "adult": false,
        "backdrop_path": "/qViFGWCHaSmW4gP00RGh3xjMjsP.jpg",
        "genre_ids": [27, 9648],
        "id": 758724,
        "original_language": "en",
        "original_title": "The Cellar",
        "overview": "Дочь Киры Вудс таинственным образом исчезает в подвале их нового загородного дома. Вскоре Кира обнаруживает, что дом контролирует древняя и могущественная сущность, с которой ей придется сразиться, чтобы защитить души близких.",
        "popularity": 1192.076,
        "poster_path": "/ieq1dlpVCWFA60C7ADWjntNzkFq.jpg",
        "release_date": "2022-05-12",
        "title": "Заклятье: Спуск к дьяволу",
        "video": false,
        "vote_average": 6.5,
        "vote_count": 129
    }, {
        "adult": false,
        "backdrop_path": "/k2G4WqGiT60K9yJnPh4K6VLnl3A.jpg",
        "genre_ids": [28, 12, 14],
        "id": 639933,
        "original_language": "en",
        "original_title": "The Northman",
        "overview": "Конец IX века, небольшой остров в Северной Атлантике. Король Орвандилл с серьёзным ранением возвращается из похода к жене Гудрун и юному сыну Амлету. Мечтая отправиться на очередное сражение и умереть на поле боя, он передаёт трон сыну, но тут же погибает от руки брата Фьолнира — тот отрубает монарху голову и забирает королевство и Гудрун себе. Мальчику удаётся сбежать. Спустя десятилетия Амлет вырастает в крепкого безжалостного викинга и однажды в очередной разорённой деревне встречает ведьму, которая наставляет его на пусть мести. Узнав, что Фьолнир с Гудрун поселились в Исландии, Амлет отправляется туда с партией славянских рабов. На борту его внимание привлекает Ольга из Березового леса.",
        "popularity": 1156.888,
        "poster_path": "/aNlKvl91MTLKc5i59SxrxAlXLlT.jpg",
        "release_date": "2022-04-21",
        "title": "Варяг",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 2145
    }, {
        "adult": false,
        "backdrop_path": "/33qGtN2GpGEb94pn25PDPeWQZLk.jpg",
        "genre_ids": [28, 80, 53],
        "id": 894169,
        "original_language": "en",
        "original_title": "Vendetta",
        "overview": "Бывший морпех Уильям Дункан теряет дочь — девушка стала случайной жертвой разборок уличных банд. Полиция бездействует. Отец берет правосудие в свои руки и расправляется с виновным. Убитый оказывается сыном крупного мафиози, и Дункан попадает в эпицентр войны бандитских группировок.",
        "popularity": 1154.556,
        "poster_path": "/4Svi7Kmez5SN1ytp19wgtDHedBS.jpg",
        "release_date": "2022-06-09",
        "title": "Вендетта. Банды Атланты",
        "video": false,
        "vote_average": 6.5,
        "vote_count": 137
    }, {
        "adult": false,
        "backdrop_path": "/3myU9OTSvAXxFVYBDUDs9zDFF4P.jpg",
        "genre_ids": [27, 53],
        "id": 629015,
        "original_language": "en",
        "original_title": "Shut In",
        "overview": "Джессика с двумя маленькими детьми живёт в ветхом доме в сельской глуши. Даже такое жильё ей не по карману, поэтому девушка решает переехать, о чём и сообщает внезапно зашедшему в гости бывшему бойфренду. Тот, подстрекаемый дружком-наркоманом, выходит из себя и запирает Джессику в кладовке — теперь ей придётся проявить немалую изобретательность, чтобы выбраться из этой ситуации и спасти детей.",
        "popularity": 1145.058,
        "poster_path": "/awmaQuMN0NE52au6cJQLN69qH1A.jpg",
        "release_date": "2022-03-24",
        "title": "Взаперти",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 172
    }, {
        "adult": false,
        "backdrop_path": "/t0mwKhUDa62hdhdKSsN4xMfhY5Z.jpg",
        "genre_ids": [18, 35],
        "id": 626735,
        "original_language": "en",
        "original_title": "Dog",
        "overview": "Профессиональный военный Джексон Бриггс всеми силами пытается вернуться в строй, но из-за травмы головы получает постоянные отказы. Когда умирает один из его сослуживцев, Бриггсу дают задание: с военной базы в штате Вашингтон доставить на похороны в аризонский Ногалес боевую подругу почившего — нервную бельгийскую овчарку Лулу с целым спектром посттравматических расстройств. Поскольку собака боится летать, сделать это придётся на машине по Тихоокеанскому побережью, и эта поездка будет не самым простым заданием Бриггса.",
        "popularity": 1124.075,
        "poster_path": "/9FkX7hq6r1EhONzTUJHZPwY0qi5.jpg",
        "release_date": "2022-02-23",
        "title": "Лулу и Бриггс",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 778
    }, {
        "adult": false,
        "backdrop_path": "/g3pG27i0v6eKWDKLf4GQsKZxmZX.jpg",
        "genre_ids": [53, 28],
        "id": 888195,
        "original_language": "en",
        "original_title": "Hot Seat",
        "overview": "Орландо — бывший хакер, который вынужден вновь взяться за старое, оказавшись мишенью таинственного кибер-террориста. Серия взрывов по всему городу доказывает, что кто бы это ни затеял — он не шутит. Орландо приходится выполнить ряд заданий, ведь на счету не только его жизнь, но и жизни его близких, а время на исходе. И полиция, и сапёры уверены, что именно Орландо — инициатор этой взрывной игры.",
        "popularity": 1057.08,
        "poster_path": "/kwedSNh0USGccaV5uveBvMIiwCj.jpg",
        "release_date": "2022-07-08",
        "title": "Взрывная игра",
        "video": false,
        "vote_average": 6.3,
        "vote_count": 38
    }, {
        "adult": false,
        "backdrop_path": "/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg",
        "genre_ids": [28, 12],
        "id": 335787,
        "original_language": "en",
        "original_title": "Uncharted",
        "overview": "Нейтан Дрейк и Виктор «Салли» Салливан, два искателя приключений, отправляются на поиски величайшего сокровища мира. Кроме того, они надеются найти улики, которые приведут их к давно потерянному брату Нейтана.",
        "popularity": 1036.919,
        "poster_path": "/s04r9V6BX1FO2INzc2DL21UW57T.jpg",
        "release_date": "2022-02-10",
        "title": "Анчартед: На картах не значится",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 3097
    }, {
        "adult": false,
        "backdrop_path": "/vjnLXptqdxnpNJer5fWgj2OIGhL.jpg",
        "genre_ids": [28, 53, 80],
        "id": 818397,
        "original_language": "en",
        "original_title": "Memory",
        "overview": "Он был первоклассным киллером всю жизнь.  Но стоило ему, следуя своему моральному кодексу, отказаться от заказа, на него объявили охоту.  Он готов применить все свои навыки, чтобы заставить виновных заплатить, но постепенно угасающая память путает ему все карты...",
        "popularity": 997.11,
        "poster_path": "/hl5bEobNp0wpVxGVTItkcER0FjQ.jpg",
        "release_date": "2022-04-28",
        "title": "Флешбэк",
        "video": false,
        "vote_average": 7.3,
        "vote_count": 687
    }],
    "total_pages": 979,
    "total_results": 19568
}
export const baseUrls = { "images": { "base_url": "http://image.tmdb.org/t/p/", "secure_base_url": "https://image.tmdb.org/t/p/", "backdrop_sizes": ["w300", "w780", "w1280", "original"], "logo_sizes": ["w45", "w92", "w154", "w185", "w300", "w500", "original"], "poster_sizes": ["w92", "w154", "w185", "w342", "w500", "w780", "original"], "profile_sizes": ["w45", "w185", "h632", "original"], "still_sizes": ["w92", "w185", "w300", "original"] }, "change_keys": ["adult", "air_date", "also_known_as", "alternative_titles", "biography", "birthday", "budget", "cast", "certifications", "character_names", "created_by", "crew", "deathday", "episode", "episode_number", "episode_run_time", "freebase_id", "freebase_mid", "general", "genres", "guest_stars", "homepage", "images", "imdb_id", "languages", "name", "network", "origin_country", "original_name", "original_title", "overview", "parts", "place_of_birth", "plot_keywords", "production_code", "production_companies", "production_countries", "releases", "revenue", "runtime", "season", "season_number", "season_regular", "spoken_languages", "status", "tagline", "title", "translations", "tvdb_id", "tvrage_id", "type", "video", "videos"] }